stages:
  prepare_images:
    cmd: python refine_masati.py
    deps:
    - MASATI-v2/
    - refine_masati.py
    outs:
    - PNGImages
    - xml_annotations
  get_yolo_labels:
    cmd: python convert_xml_to_yolotxt.py
    deps:
    - PNGImages/
    - modified_xml_annotations/
    - convert_xml_to_yolotxt.py
    outs:
    - yolo_annotations
  split_dataset:
    cmd: python train_test_split.py
    deps:
    - PNGImages/
    - train_test_split.py
    - modified_xml_annotations/
    params:
    - split_dataset.annotations_dir
    - split_dataset.trainpct
    outs:
    - train/
    - validation/
    - xml_annotations_test.txt
    - xml_annotations_train.txt
  get_json_labels:
    cmd: python convert_masatixml_to_json_labels.py
    deps:
    - convert_masatixml_to_json_labels.py
    - xml_annotations_test.txt
    - xml_annotations_train.txt
    params:
    - get_json_labels.classes
    - get_json_labels.is_masati
    - get_json_labels.output_json_test
    - get_json_labels.output_json_train
    - get_json_labels.test_labels
    - get_json_labels.train_labels
    outs:
    - coco_json_annotations/annotations_test.json
    - coco_json_annotations/annotations_train.json
  modify_annotations:
    cmd: python remove_extra_classes.py
    deps:
    - remove_extra_classes.py
    - xml_annotations/
    outs:
    - modified_xml_annotations/
  sort_yolo_file_structure:
    cmd: python sort_yolo_images.py
    deps:
    - sort_yolo_images.py
    - train/
    - validation/
    - yolo_annotations/
    outs:
    - yolo_images_train/
    - yolo_images_validation/
    - yolo_labels_train/
    - yolo_labels_validation/
  prepare_yolov5_data_structure:
    cmd: python prepare_yolov5.py
    deps:
    - prepare_yolov5.py
    params:
    - create_yolov5_filestructure.dataset
    - create_yolov5_filestructure.train_imgs
    - create_yolov5_filestructure.train_labels
    - create_yolov5_filestructure.val_imgs
    - create_yolov5_filestructure.val_labels
    outs:
    - ../../data/masati/
