stages:
  prepare_images:
    cmd: python refine_masati.py
    deps:
    - MASATI-v2/
    - refine_masati.py
    outs:
    - PNGImages
    - xml_annotations
  get_yolo_labels:
    cmd: python convert_xml_to_yolotxt.py
    deps:
    - PNGImages/
    - xml_annotations/
    - convert_xml_to_yolotxt.py
    outs:
    - yolo_annotations
  split_dataset:
    cmd: python train_test_split.py
    deps:
    - PNGImages/
    - train_test_split.py
    - xml_annotations/
    params:
    - split_dataset.annotations_dir
    - split_dataset.trainpct
    outs:
    - train/
    - validation/
    - xml_annotations_test.txt
    - xml_annotations_train.txt
