split_dataset:
  annotations_dir: modified_xml_annotations
  trainpct: 0.75
  train_dir: train
  valid_dir: validation
  img_dir: images
  file_type: png
get_json_labels:
  train_labels: xml_annotations_train.txt
  test_labels: xml_annotations_test.txt
  is_masati: True
  classes: ["boat"]
  output_json_train: annotations_train.json
  output_json_test: annotations_test.json
create_yolov5_filestructure:
  dataset: masati
  train_labels: yolo_labels_train
  val_labels: yolo_labels_validation
  train_imgs: yolo_images_train
  val_imgs: yolo_images_validation