split_dataset:
  annotations_dir: modified_xml_annotations
  trainpct: 0.75
get_json_labels:
  train_labels: xml_annotations_train.txt
  test_labels: xml_annotations_test.txt
  is_masati: True
  classes: ["boat"]
  output_json_train: annotations_train.json
  output_json_test: annotations_test.json