stages:
  get_yolo_annotations:
    cmd: python convert_xml_to_yolotxt.py
    deps:
    - convert_xml_to_yolotxt.py
    - images/
    - xml_annotations
    outs:
    - yolo_annotations
  prepare_yolov5_data_structure:
    cmd: python prepare_yolov5.py
    deps:
    - prepare_yolov5.py
    params:
    - create_yolov5_filestructure.dataset
    - create_yolov5_filestructure.train_imgs
    - create_yolov5_filestructure.train_labels
    - create_yolov5_filestructure.val_imgs
    - create_yolov5_filestructure.val_labels
    outs:
    - ../../data/sassoon/
