stages:
  get_yolo_annotations:
    cmd: python convert_xml_to_yolotxt.py
    deps:
    - convert_xml_to_yolotxt.py
    - images/
    - xml_annotations
    outs:
    - yolo_annotations
  split_dataset:
    cmd: python train_test_split.py
    deps:
    - images/
    - train_test_split.py
    - xml_annotations
    params:
    - split_dataset.annotations_dir
    - split_dataset.trainpct
    outs:
    - train/
    - validation/
    - xml_annotations_test.txt
    - xml_annotations_train.txt
  sort_yolo_file_structure:
    cmd: python sort_yolo_images.py
    deps:
    - sort_yolo_images.py
    - train/
    - validation/
    - yolo_annotations/
    outs:
    - yolo_images_train/
    - yolo_images_validation/
    - yolo_labels_train/
    - yolo_labels_validation/
  prepare_yolov5_data_structure:
    cmd: python prepare_yolov5.py
    deps:
    - prepare_yolov5.py
    params:
    - create_yolov5_filestructure.dataset
    - create_yolov5_filestructure.train_imgs
    - create_yolov5_filestructure.train_labels
    - create_yolov5_filestructure.val_imgs
    - create_yolov5_filestructure.val_labels
    outs:
    - ../../data/sassoon/
